
server:
  port: 8080
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/click_app
      username: postgres
      password: user

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  sql.init:
    mode: never

  properties:
    hibernate:
      enable_lazy_load_no_trans: true
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

